### ISSUE TITLE
An issue with patch predictor example, related to "mask_reader", while using WSI mode

### ISSUE THREAD

**Issue by HammamGh** [TIA-Lab/tiatoolbox#125]
* TIA Toolbox version: 0.6.0
* Python version: 3.7
* Operating System: Win10

### Description

First of all, many thanks to all the contributors for this great & valuable effort preparing this toolbox. I am using the _patch predictor example_ and I had two issues:

(1) when I run the pre-trained model: [[ pretrained_model='resnet18-kather100k' ]] on the validation dataset downloaded from the Warwick tiatoolbox dataset page. Then, found that the accuracy was low. After debugging, realized that the provided order of classes is not the same as it was trained with (not sure if this issue is only with me). Anyway, I changed it accordingly and got good accuracy and thought it might be useful to report this issue ( the updated order can be found in the next section).

(2) I had an issue while predicting the mask using the same pre-trained network but on the wsi mode.

### What I Did

**For issue (1):**

That is the previous class order:
```
label_dict = {'ADI': 0, 'BACK': 1, 'DEB': 2, 'LYM': 3, 'MUC': 4, 'MUS': 5, 'NORM': 6, 'STR': 7, 'TUM': 8}
```

This is the updated order that was working for me:
```
label_dict = {'BACK': 0, 'NORM': 1, 'DEB': 2, 'TUM': 3, 'ADI': 4, 'MUC': 5, 'MUS': 6, 'STR': 7, 'LYM': 8}
```

**For issue (2):**
The commands I used were as follows:

```
predictor = CNNPatchPredictor(pretrained_model='resnet18-kather100k', batch_size=64)
wsi_output = predictor.predict([wsi_file_name],
                           mode='wsi',
                           stride_size=(112,112),
                           return_probabilities=True)
```

### The traceback for issue (2) here:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.2\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 5, in <module>
  File "D:\Hammam\Research\TILs\TIL_project\2_Expermients_including_codes_and_results\code\pre-process\TIA_toolbox\tiatoolbox_example\tiatoolbox\models\classification\patch_predictor.py", line 435, in predict
    units=units,
  File "D:\Hammam\Research\TILs\TIL_project\2_Expermients_including_codes_and_results\code\pre-process\TIA_toolbox\tiatoolbox_example\tiatoolbox\models\dataset\classification.py", line 310, in __init__
    units=units,
  File "D:\Hammam\Research\TILs\TIL_project\2_Expermients_including_codes_and_results\code\pre-process\TIA_toolbox\tiatoolbox_example\tiatoolbox\tools\patchextraction.py", line 170, in filter_coordinates
    raise ValueError("`mask_reader` should be wsireader.VirtualWSIReader.")
ValueError: `mask_reader` should be wsireader.VirtualWSIReader.
```

Any help would be much appreciated,
Thanks & best regards,
Hammam

**Comment by vqdang** [comment]
Related to the progress in #109
